// <auto-generated />
using System;
using InternshipTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipTrackerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204063844_PhoneNumberCreated")]
    partial class PhoneNumberCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InternshipTrackerAPI.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Internships", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Safaricom",
                            DateApplied = new DateTime(2026, 1, 30, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(6059),
                            IsActive = true,
                            JobUrl = "https://safaricom.com/careers",
                            RoleTitle = "Software Engineering Intern",
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft ADC",
                            DateApplied = new DateTime(2026, 1, 4, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(6067),
                            IsActive = false,
                            JobUrl = "https://careers.microsoft.com",
                            RoleTitle = "Program Manager Intern",
                            Status = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Cellulant",
                            DateApplied = new DateTime(2026, 2, 4, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(6137),
                            IsActive = true,
                            JobUrl = "https://cellulant.io/jobs",
                            RoleTitle = "Backend Developer",
                            Status = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("InternshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternshipId");

                    b.ToTable("Notes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Spoke with Sarah. Asked about C# experience.",
                            DateCreated = new DateTime(2026, 1, 31, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(6994),
                            InternshipId = 1,
                            Title = "HR Screening"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Received link for coding assessment.",
                            DateCreated = new DateTime(2026, 2, 3, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(6997),
                            InternshipId = 1,
                            Title = "Technical Interview Invite"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Standard automated reply.",
                            DateCreated = new DateTime(2026, 1, 6, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(7000),
                            InternshipId = 2,
                            Title = "Rejection Email"
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 4, 6, 38, 43, 602, DateTimeKind.Utc).AddTicks(4890),
                            Email = "student@uni.edu",
                            PasswordHash = "student@123",
                            PhoneNumber = "",
                            Username = "student1"
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Internship", b =>
                {
                    b.HasOne("InternshipTrackerAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Note", b =>
                {
                    b.HasOne("InternshipTrackerAPI.Models.Internship", "Internship")
                        .WithMany()
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");
                });
#pragma warning restore 612, 618
        }
    }
}
