// <auto-generated />
using System;
using InternshipTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipTrackerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123074805_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InternshipTrackerAPI.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Internships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Safaricom",
                            DateApplied = new DateTime(2026, 1, 18, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1231),
                            IsActive = true,
                            JobUrl = "https://safaricom.com/careers",
                            RoleTitle = "Software Engineering Intern",
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft ADC",
                            DateApplied = new DateTime(2025, 12, 23, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1242),
                            IsActive = false,
                            JobUrl = "https://careers.microsoft.com",
                            RoleTitle = "Program Manager Intern",
                            Status = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Cellulant",
                            DateApplied = new DateTime(2026, 1, 23, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1243),
                            IsActive = true,
                            JobUrl = "https://cellulant.io/jobs",
                            RoleTitle = "Backend Developer",
                            Status = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("InternshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternshipId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Spoke with Sarah. Asked about C# experience.",
                            DateCreated = new DateTime(2026, 1, 19, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1269),
                            InternshipId = 1,
                            Title = "HR Screening"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Received link for coding assessment.",
                            DateCreated = new DateTime(2026, 1, 22, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1271),
                            InternshipId = 1,
                            Title = "Technical Interview Invite"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Standard automated reply.",
                            DateCreated = new DateTime(2025, 12, 25, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1272),
                            InternshipId = 2,
                            Title = "Rejection Email"
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 23, 7, 48, 5, 48, DateTimeKind.Utc).AddTicks(1060),
                            Email = "student@uni.edu",
                            PasswordHash = "$2a$11$uIvxJyfCWMRnPipkDTuC8Oh26zgd8y/khAhLcu7dHtQJq8F4l3waa",
                            Username = "student1"
                        });
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Internship", b =>
                {
                    b.HasOne("InternshipTrackerAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipTrackerAPI.Models.Note", b =>
                {
                    b.HasOne("InternshipTrackerAPI.Models.Internship", "Internship")
                        .WithMany()
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");
                });
#pragma warning restore 612, 618
        }
    }
}
